### ISSUE TITLE
屏蔽功能失效

### ISSUE THREAD

**Issue by pakchoiko** [dozer47528/zhihu-block-chrome-extension#1]
下载安装1.2版本后发现没有屏蔽,是知乎改版了原因吗?

**Comment by dozer47528** [comment]
是的，知乎大改版了，而且现在知乎有自己的屏蔽功能了，手机端可以根据用户、话题等纬度屏蔽内容了。
所以这个插件没什么太大的意义了。

**Comment by xzhlksh** [comment]
@dozer47528 求大神更新啊
知乎现在的屏蔽的确是可以屏蔽黑名单用户的回答了，但还是不能屏蔽该用户的分享。

**Comment by yzmyyff** [comment]
求更新, 屏蔽名单最好可以将该用户的所有消息彻底删除

**Comment by dozer47528** [comment]
知乎更新了UI，新版本已经无法使用
